version: '3.9'

services:
  mapfish_print:
    image: camptocamp/mapfish_print:3.30
    container_name: mapfish_print
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGSCHEMA: ${PGSCHEMA}
      CATALINA_OPTS: >-
        -Ddb.host=${PGHOST}
        -Ddb.port=${PGPORT}
        -Ddb.username=${PGUSER}
        -Ddb.password=${PGPASSWORD}
        -Ddb.name=${PGDATABASE}
        -Ddb.schema=${PGSCHEMA}
    volumes:
      - ./print-apps:/usr/local/tomcat/webapps/ROOT/print-apps
      - ./fonts:/usr/share/fonts/truetype
    networks:
      - postgis_default

networks:
  postgis_default:
    external: true
